//! kanata configuration generator.
//!
//! Toggle semantics (per the user's driver): on `CapsLock` press the
//! Ctrl+Win+F24 chord is tapped (all three keys down, released in reverse —
//! a real chord, never a lone Win tap) and the `mouse` layer activates; on
//! `CapsLock` release the chord is tapped again via `on-release-fakekey`.
//! The chord tap is what makes the system's touchpad driver flip the touchpad
//! on and off; the application never touches devices.

use crate::config::AppConfig;
use crate::keys::{HOLD_KEY, KEY_NONE};

/// The kanata action for a `mouse`-layer slot, given the action-to-key
/// mapping. Unassigned slots emit `XX` (blocked).
///
/// The check order mirrors the claim order of [`layer_keys`] (left click →
/// middle click → right click → `CapsLock`), so when two actions share one key
/// the documented "first claim wins" rule really holds — previously the
/// `CapsLock` check ran first and silently swallowed a click binding that had
/// first claim on the shared key.
#[must_use]
pub fn layer_slot_action(
    slot: &str,
    left_click_key: &str,
    middle_click_key: &str,
    right_click_key: &str,
    capslock_key: &str,
) -> &'static str {
    if slot == left_click_key {
        "mlft"
    } else if slot == middle_click_key {
        "mmid"
    } else if slot == right_click_key {
        "mrgt"
    } else if slot == capslock_key {
        "caps"
    } else {
        "XX"
    }
}

/// Ordered, de-duplicated list of layer keys to place in `defsrc`.
///
/// `CapsLock` never appears: the physical key owns that defsrc slot as the
/// layer hold key, so binding it to an action would be a silent no-op.
fn layer_keys(cfg: &AppConfig) -> Vec<&str> {
    let mut keys: Vec<&str> = Vec::new();
    for k in [
        cfg.left_click_key.as_str(),
        cfg.middle_click_key.as_str(),
        cfg.right_click_key.as_str(),
        cfg.capslock_key.as_str(),
    ] {
        if k != KEY_NONE && k != HOLD_KEY && !keys.contains(&k) {
            keys.push(k);
        }
    }
    keys
}

/// Generate the kanata layer config from the app configuration.
///
/// Layer keys are emitted in `defsrc` once each (duplicate action-to-key
/// assignments collapse to the first claim), and every slot passes its own key
/// through unchanged on the base layer.
#[must_use]
pub fn generate_config_text(cfg: &AppConfig) -> String {
    let keys = layer_keys(cfg);
    let caps_slot = if cfg.feature_enabled {
        r"(multi
    (layer-while-held mouse)
    (macro C-M-f24)
    (on-release-fakekey release-tap tap))"
            .to_string()
    } else {
        "caps".to_string()
    };
    let slot = |k: &str| {
        layer_slot_action(
            k,
            &cfg.left_click_key,
            &cfg.middle_click_key,
            &cfg.right_click_key,
            &cfg.capslock_key,
        )
    };
    let base_slots: Vec<String> = std::iter::once(caps_slot)
        .chain(keys.iter().map(|k| (*k).to_string()))
        .collect();
    let mouse_slots: Vec<String> = std::iter::once("XX".to_string())
        .chain(keys.iter().map(|k| slot(k).to_string()))
        .collect();
    let defsrc = std::iter::once("caps")
        .chain(keys.iter().copied())
        .collect::<Vec<_>>()
        .join(" ");
    let enumerated = |slots: &[String]| {
        slots
            .iter()
            .map(|s| format!("  {s}"))
            .collect::<Vec<_>>()
            .join("\n")
    };
    format!(
        ";; generated by enable-touchpad — edits are overwritten by the app\n\
         (defcfg process-unmapped-keys no)\n\
         \n\
         (defsrc {defsrc})\n\
         \n\
         (deffakekeys\n  release-tap (macro C-M-f24))\n\
         \n\
         (deflayer base\n{}\n)\n\
         \n\
         (deflayer mouse\n{}\n)\n",
        enumerated(&base_slots),
        enumerated(&mouse_slots)
    )
}

#[cfg(test)]
mod tests {
    use super::generate_config_text;
    use crate::config::AppConfig;
    use crate::keys::KEY_NONE;

    fn cfg(feature_enabled: bool, left: &str, middle: &str, right: &str, caps: &str) -> AppConfig {
        AppConfig {
            feature_enabled,
            left_click_key: left.to_string(),
            middle_click_key: middle.to_string(),
            right_click_key: right.to_string(),
            capslock_key: caps.to_string(),
        }
    }

    #[test]
    fn generator_dedups_keys_and_keeps_first_claim() {
        let cfg = cfg(true, "KeyF", "KeyF", KEY_NONE, "KeyJ");
        let text = generate_config_text(&cfg);
        assert!(text.contains("(defsrc caps KeyF KeyJ)"), "{text}");
        assert!(
            text.contains(
                "(deflayer base\n  (multi\n    (layer-while-held mouse)\n    (macro C-M-f24)\n    (on-release-fakekey release-tap tap))\n  KeyF\n  KeyJ\n)"
            ),
            "{text}"
        );
        assert!(
            text.contains("(deflayer mouse\n  XX\n  mlft\n  caps\n)"),
            "{text}"
        );
    }

    #[test]
    fn generator_ignores_hold_key_collision() {
        let cfg = cfg(true, "CapsLock", "KeyW", "KeyE", "lalt");
        let text = generate_config_text(&cfg);
        assert!(text.contains("(defsrc caps KeyW KeyE lalt)"), "{text}");
        assert!(
            text.contains("(deflayer mouse\n  XX\n  mmid\n  mrgt\n  caps\n)"),
            "{text}"
        );
    }

    #[test]
    fn generator_none_only_emits_caps() {
        let cfg = cfg(true, KEY_NONE, KEY_NONE, KEY_NONE, KEY_NONE);
        let text = generate_config_text(&cfg);
        assert!(text.contains("(defsrc caps)"), "{text}");
        assert!(text.contains("(deflayer mouse\n  XX\n)"), "{text}");
    }

    #[test]
    fn generator_disabled_feature_passes_caps_through() {
        let cfg = cfg(false, "q", "w", "e", "lalt");
        let text = generate_config_text(&cfg);
        assert!(
            text.contains("(deflayer base\n  caps\n  q\n  w\n  e\n  lalt\n)"),
            "{text}"
        );
    }

    #[test]
    fn generator_click_vs_caps_conflict_resolves_by_first_claim() {
        // 左键 and CapsLock sharing one key: the left click has first claim
        // (claim order left → middle → right → caps), so the mouse layer must
        // map the key to `mlft`, not silently to `caps`.
        let cfg = cfg(true, "KeyJ", KEY_NONE, KEY_NONE, "KeyJ");
        let text = generate_config_text(&cfg);
        assert!(text.contains("(defsrc caps KeyJ)"), "{text}");
        assert!(text.contains("(deflayer mouse\n  XX\n  mlft\n)"), "{text}");
    }
}
